development: &default
  client_id: <%= Rails.application.credentials.paypal[:client_id] %>
  client_secret: <%= Rails.application.credentials.paypal[:client_secret] %>
  ssl_options:
    ca_file: null

test:
  <<: *default